# Generated by Django 3.0.1 on 2020-05-29 20:49

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_price', models.PositiveIntegerField()),
                ('p_discount_price', models.FloatField(blank=True, null=True)),
                ('p_brand', models.CharField(choices=[('VIN', 'VINCENT CHASE'), ('JOHN', 'JOHN JACOBS'), ('RAY', 'RAY-BAN'), ('CARRERA', 'CARRERA'), ('OAKLEY', 'OAKLEY'), ('TOMMY', 'TOMMY HILFIGURE'), ('VOGUE', 'VOGUE')], default='VIN', max_length=50)),
                ('p_description', models.TextField(max_length=500)),
                ('p_features', models.TextField(blank=True)),
                ('p_publish_date', models.DateTimeField(auto_now_add=True)),
                ('p_category', models.CharField(choices=[('NEW ARRIVAL', 'New Arival'), ('R', 'RayBan'), ('P', 'Polarised'), ('T', 'Titan Eye')], default='N', max_length=20)),
                ('p_sub_category', models.CharField(choices=[('CLASSIC', 'CLASSIC EYEGLASSES'), ('PREMIUM', 'PREMIUM EYEGLASSES'), ('ECONOMY', 'ECONOMY EYEGLASSES'), ('0 POWER', '0 POWER BLUE GLASSES')], default='CLASSIC', max_length=100)),
                ('p_frame_type', models.CharField(choices=[('REACT', 'RECTANGLE'), ('WAY', 'WAYFARER'), ('ROUND', 'ROUNDED'), ('AVIATOR', 'AVIATOR'), ('CAT-E', 'CAT-EYE'), ('RIM-L', 'RIMLESS'), ('HALF-R', 'HALF-RIM')], default='REACT', max_length=100)),
                ('p_style', models.CharField(default='TR FLEX', max_length=100)),
                ('p_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('C', 'CHILD')], default='M', max_length=50)),
                ('p_total_Item', models.PositiveIntegerField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('p_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keekers.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='keekers.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offText', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('pd_category', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='keekers.Item')),
            ],
        ),
    ]
