# Generated by Django 3.0.1 on 2020-05-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='p_brand',
            field=models.CharField(choices=[('VINCENT CHASE', 'VINCENT CHASE'), ('JOHN JACOBS', 'JOHN JACOBS'), ('RAY-BAN', 'RAY-BAN'), ('CARRERA', 'CARRERA'), ('OAKLEY', 'OAKLEY'), ('TOMMY HILFIGURE', 'TOMMY HILFIGURE'), ('VOGUE', 'VOGUE')], default='VINCENT CHASE', max_length=50),
        ),
    ]
