# Generated by Django 3.0.1 on 2020-05-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0002_auto_20200530_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
