# Generated by Django 3.0.1 on 2020-05-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0004_auto_20200530_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
