# Generated by Django 3.0.1 on 2020-07-24 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keekers', '0009_auto_20200531_1215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Cart',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total',
            field=models.BigIntegerField(default=1),
        ),
    ]
