# Generated by Django 3.0.1 on 2020-08-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0011_auto_20200724_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='p_image_sub_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_10',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_4',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_5',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_6',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_7',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_8',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AddField(
            model_name='item',
            name='p_image_sub_9',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='p_image',
            field=models.ImageField(upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
