# Generated by Django 3.0.1 on 2020-08-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0012_auto_20200809_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='p_image',
            field=models.ImageField(upload_to='images//'),
        ),
    ]
