# Generated by Django 3.0.1 on 2020-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0014_auto_20200809_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='p_image',
            field=models.ImageField(upload_to='images/123/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='p_image_sub_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/123/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='p_image_sub_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/123/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='p_image_sub_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/123/'),
        ),
    ]
