# Generated by Django 3.0.1 on 2020-08-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keekers', '0016_auto_20200809_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
