# Generated by Django 3.0.1 on 2020-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=100)),
                ('e_email', models.EmailField(max_length=254)),
                ('e_post', models.CharField(choices=[('HR', 'HR'), ('Developer', 'Developer'), ('Maneger', 'Maneger')], default='', max_length=100)),
                ('e_salary', models.BigIntegerField()),
                ('e_bank_AC_no', models.CharField(max_length=500)),
                ('e_bank_AC_Branch', models.CharField(max_length=100)),
                ('e_bank_AC_IFSC_CODE', models.CharField(max_length=100)),
                ('e_photo', models.ImageField(upload_to='images/Employee_profile')),
                ('e_qualification', models.TextField()),
                ('e_CV', models.FileField(upload_to='images/Employee_profile/CV')),
                ('e_contact', models.CharField(max_length=10)),
                ('e_joining_date', models.DateTimeField(auto_now_add=True)),
                ('e_experience', models.CharField(default='Year:0 Months:0 Days:0 ', max_length=20)),
            ],
        ),
    ]
