# Generated by Django 3.0.1 on 2020-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_experience',
            field=models.CharField(default='Year:0 Months:0 Days:0 ', max_length=22),
        ),
    ]
